#!/usr/bin/env python3
""" Task 1: 1. Same Convolution """
import numpy as np


def convolve_grayscale_same(images, kernel):
    """
    Perform a same convolution on grayscale images.

    This convolution preserves the height and width of the input images by
    applying zero padding based on the kernel size.

    Parameters:
    images (numpy.ndarray):
    A numpy array of shape (m, h, w) containing m grayscale images,
    each of height h and width w.
    kernel (numpy.ndarray):
    A numpy array of shape (kh, kw) representing the convolution kernel,
    where kh is the height and kw is the width of the kernel.

    Returns:
    numpy.ndarray:
    A numpy array of shape (m, h, w) containing the result of the convolution,
    where h and w are the original height and width of the input images.
    The output is generated by applying zero padding to the input images.
    """
    m, h, w = images.shape  # Number of images, height, and width
    kh, kw = kernel.shape   # Kernel height and width

    # Calculate padding for height and width
    pad_h = kh // 2
    pad_w = kw // 2

    # Apply zero padding to the images, accounting for even-sized kernels
    images_padded = np.pad(images,
                           pad_width=((0, 0), (pad_h, kh - pad_h - 1),
                                      (pad_w, kw - pad_w - 1)),
                           mode='constant', constant_values=0)

    # Initialize output array for the filtered images
    image_filter = np.zeros((m, h, w))

    # Perform the convolution operation
    for i in range(h):
        for j in range(w):
            image_filter[:, i, j] = (kernel *
                                     images_padded[:, i:i+kh, j:j+kw])\
                                         .sum(axis=(1, 2))

    return image_filter
